import AppKit
import Foundation

enum ColorSchemePreference: String, CaseIterable {
    case auto
    case light
    case dark

    var displayName: String {
        switch self {
        case .auto: return "Auto"
        case .light: return "Light"
        case .dark: return "Dark"
        }
    }

    var nsAppearance: NSAppearance? {
        switch self {
        case .auto: return nil
        case .light: return NSAppearance(named: .aqua)
        case .dark: return NSAppearance(named: .darkAqua)
        }
    }
}

@MainActor
final class AppSettingsStore: ObservableObject {
    @Published var cliPath: String {
        didSet { UserDefaults.standard.set(cliPath, forKey: Keys.cliPath) }
    }

    @Published var keepDataURIs: Bool {
        didSet { UserDefaults.standard.set(keepDataURIs, forKey: Keys.keepDataURIs) }
    }

    @Published var colorScheme: ColorSchemePreference {
        didSet { UserDefaults.standard.set(colorScheme.rawValue, forKey: Keys.colorScheme) }
    }

    init() {
        let defaults = UserDefaults.standard
        let bundledPath = Self.bundledMarkitdownPath()
        let savedPath = defaults.string(forKey: Keys.cliPath)
        
        // Use bundled path if available, otherwise use saved path, otherwise use default
        self.cliPath = bundledPath ?? savedPath ?? "/Users/abirmajumdar/.local/bin/markitdown"
        self.keepDataURIs = defaults.object(forKey: Keys.keepDataURIs) as? Bool ?? false
        let savedScheme = defaults.string(forKey: Keys.colorScheme)
        self.colorScheme = savedScheme.flatMap(ColorSchemePreference.init(rawValue:)) ?? .auto
    }

    func validationError() -> String? {
        if cliPath.isEmpty {
            return "MarkItDown CLI path cannot be empty."
        }

        var isDirectory: ObjCBool = false
        guard FileManager.default.fileExists(atPath: cliPath, isDirectory: &isDirectory), !isDirectory.boolValue else {
            return "MarkItDown CLI path does not point to a file."
        }

        guard FileManager.default.isExecutableFile(atPath: cliPath) else {
            return "MarkItDown CLI is not executable."
        }

        return nil
    }

    static func bundledMarkitdownPath() -> String? {
        // Packaged app: resources live under Contents/Resources/markitdown/markitdown.
        // Check this first — Bundle.module crashes with fatalError() when the SwiftPM
        // resource bundle is absent (which is the case in a distributed .app where
        // resources are copied directly into Contents/Resources/ rather than a .bundle).
        if let bundlePath = Bundle.main.resourcePath {
            let markitdownPath = (bundlePath as NSString).appendingPathComponent("markitdown/markitdown")
            if FileManager.default.fileExists(atPath: markitdownPath),
                FileManager.default.isExecutableFile(atPath: markitdownPath) {
                return markitdownPath
            }
        }

        // Development builds (`swift build` / `swift run`): SwiftPM places resources
        // inside a named .bundle directory. We locate that bundle manually to avoid the
        // fatalError() that Bundle.module raises when the bundle is absent.
        if let bundledURL = safeModuleBundle()?.url(forResource: "markitdown", withExtension: nil) {
            let bundledPath = bundledURL.path
            if FileManager.default.fileExists(atPath: bundledPath),
                FileManager.default.isExecutableFile(atPath: bundledPath) {
                return bundledPath
            }
        }

        return nil
    }

    /// Locates the SwiftPM-generated module resource bundle without crashing.
    ///
    /// `Bundle.module` (auto-generated by SwiftPM) calls `fatalError()` when the
    /// bundle named `MarkitdownUI_MarkitdownUI.bundle` cannot be found. This helper
    /// replicates the same search paths but returns `nil` on failure instead.
    private static func safeModuleBundle() -> Bundle? {
        let bundleName = "MarkitdownUI_MarkitdownUI.bundle"
        // Replicate the candidate search paths from SwiftPM's generated Bundle.module code.
        // All candidates are only passed to Bundle(url:), which returns nil for invalid paths,
        // so no filesystem action is taken with these URLs beyond checking for a .bundle directory.
        //
        // Candidate 1: .app/Contents/Resources/  (typical packaged app resourceURL)
        // Candidate 2: three levels up → .app/Contents/ → .app/ → parent of .app
        //              (covers development builds where .bundle sits next to the .app)
        // Candidates 3-4: executable directory and its parent (covers `swift run` .build/debug/)
        let resourceURL = Bundle.main.resourceURL
        // ascends: .app/Contents/Resources/ → .app/Contents/ → .app/ → containing directory
        let appParentURL = resourceURL?
            .deletingLastPathComponent()   // → .app/Contents/
            .deletingLastPathComponent()   // → .app/
            .deletingLastPathComponent()   // → parent of .app
        let executableURL = ProcessInfo.processInfo.arguments.first.map { URL(fileURLWithPath: $0) }
        let candidates = [
            resourceURL,
            appParentURL,
            executableURL?.deletingLastPathComponent(),
            executableURL?.deletingLastPathComponent().deletingLastPathComponent(),
        ].compactMap { $0 }
        for candidate in candidates {
            let bundleURL = candidate.appendingPathComponent(bundleName)
            if let bundle = Bundle(url: bundleURL) {
                return bundle
            }
        }
        return nil
    }
}

private enum Keys {
    static let cliPath = "settings.cliPath"
    static let keepDataURIs = "settings.keepDataURIs"
    static let colorScheme = "settings.colorScheme"
}

